"""new initial configuration database

Revision ID: 8bc15a196b47
Revises: 
Create Date: 2024-10-07 17:19:53.196265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc15a196b47'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eleccion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('descripcion', sa.String(), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('persona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(), nullable=False),
    sa.Column('apellido_paterno', sa.String(), nullable=False),
    sa.Column('apellido_materno', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lista',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_eleccion', sa.Integer(), nullable=False),
    sa.Column('propuesta', sa.String(), server_default='', nullable=False),
    sa.ForeignKeyConstraint(['id_eleccion'], ['eleccion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidato',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(), nullable=False),
    sa.Column('apellido_paterno', sa.String(), nullable=False),
    sa.Column('apellido_materno', sa.String(), nullable=False),
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_lista'], ['lista.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voto',
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_elector', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_elector'], ['elector.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_lista'], ['lista.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_lista', 'id_elector')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voto')
    op.drop_table('candidato')
    op.drop_table('lista')
    op.drop_table('elector')
    op.drop_table('administrador')
    op.drop_table('persona')
    op.drop_table('eleccion')
    # ### end Alembic commands ###
