"""adding table persona, candidato, elector

Revision ID: 8c59b332e9bc
Revises: 
Create Date: 2024-08-26 18:33:31.667841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c59b332e9bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombres', sa.String(), nullable=False),
    sa.Column('apellido_paterno', sa.String(), nullable=False),
    sa.Column('apellido_materno', sa.String(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('administrador',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_administrador', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_administrador'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('elector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_persona', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_persona'], ['persona.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('elector')
    op.drop_table('administrador')
    op.drop_table('persona')
    # ### end Alembic commands ###
