"""adding 2 keys

Revision ID: a444fc7367bf
Revises: e8168f0b5535
Create Date: 2024-08-30 21:35:44.859924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a444fc7367bf'
down_revision: Union[str, None] = 'e8168f0b5535'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'voto', 'eleccion', ['id_elector'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'voto', 'lista', ['id_lista'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voto', type_='foreignkey')
    op.drop_constraint(None, 'voto', type_='foreignkey')
    # ### end Alembic commands ###
