"""update administrador id fk

Revision ID: cf9e60ce5288
Revises: 3ef8261cadf9
Create Date: 2024-08-29 23:13:13.155509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf9e60ce5288'
down_revision: Union[str, None] = '3ef8261cadf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrador', sa.Column('id_persona', sa.Integer(), nullable=True))
    op.drop_constraint('administrador_id_administrador_fkey', 'administrador', type_='foreignkey')
    op.create_foreign_key(None, 'administrador', 'persona', ['id_persona'], ['id'], ondelete='CASCADE')
    op.drop_column('administrador', 'id_administrador')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('administrador', sa.Column('id_administrador', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'administrador', type_='foreignkey')
    op.create_foreign_key('administrador_id_administrador_fkey', 'administrador', 'persona', ['id_administrador'], ['id'], ondelete='CASCADE')
    op.drop_column('administrador', 'id_persona')
    # ### end Alembic commands ###
