"""deleting votes table

Revision ID: d1cd7e4f2a19
Revises: a444fc7367bf
Create Date: 2024-08-30 21:53:32.868733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1cd7e4f2a19'
down_revision: Union[str, None] = 'a444fc7367bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voto')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voto',
    sa.Column('id_elector', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_lista', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_elector'], ['eleccion.id'], name='voto_id_elector_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_lista'], ['lista.id'], name='voto_id_lista_fkey', ondelete='CASCADE')
    )
    # ### end Alembic commands ###
