"""adding table vote

Revision ID: e8168f0b5535
Revises: cf9e60ce5288
Create Date: 2024-08-30 19:49:09.254335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8168f0b5535'
down_revision: Union[str, None] = 'cf9e60ce5288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_elector', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_elector'], ['eleccion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_lista'], ['lista.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voto')
    # ### end Alembic commands ###
