"""modifying post foreign key

Revision ID: eefac2527e18
Revises: fe6a74fec1c5
Create Date: 2024-08-30 22:37:55.855070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eefac2527e18'
down_revision: Union[str, None] = 'fe6a74fec1c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('voto_id_elector_fkey', 'voto', type_='foreignkey')
    op.create_foreign_key(None, 'voto', 'elector', ['id_elector'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voto', type_='foreignkey')
    op.create_foreign_key('voto_id_elector_fkey', 'voto', 'eleccion', ['id_elector'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
