"""adding vote table

Revision ID: fe6a74fec1c5
Revises: d1cd7e4f2a19
Create Date: 2024-08-30 21:54:28.143346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6a74fec1c5'
down_revision: Union[str, None] = 'd1cd7e4f2a19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voto',
    sa.Column('id_lista', sa.Integer(), nullable=False),
    sa.Column('id_elector', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_elector'], ['eleccion.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_lista'], ['lista.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_lista', 'id_elector')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voto')
    # ### end Alembic commands ###
